# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '100000wp_iOS' do

  use_frameworks!

  pod 'Alamofire'

  pod 'SnapKit'

  pod 'IQKeyboardManager'
  pod “SVProgressHUD”
  pod 'SDWebImage', '~>3.8'
  pod “YYModel”
  pod “FMDB”

end
