# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LakhAdd' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


use_frameworks!

pod 'Alamofire'

pod 'SnapKit'

pod 'IQKeyboardManager'
pod “SVProgressHUD”
pod 'SDWebImage', '~>3.8'
pod “YYModel”
pod “FMDB”


end
